coverage: work around two bugs in gcovr
Either gcovr 8.3 or gcc 14.2 cause an, which is also reproducible locally, when
running the job "Functional tests with code coverage, no -Werror" (see later).

This PR is an attempt at mitigating it: we transform the gcovr error in a
warning following an advice by gcovr itself.

Other (and better) strategies, such as adding `-fprofile-update=atomic` as
suggested in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68080#c4 and
documented in https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fprofile-update
did not help solve the problem.

In order to be as strict as possible, we then require that a fixed, hard coded
set of warnings must be generated, because we want to be aware of every possible
variation in the coverage analysis.

In the process, we have to counter-hack gcovr, that diabolically behaves
differently when it detects that it is running in a GitHub worker
(https://github.com/gcovr/gcovr/blob/0a426ca4baae56607f7cff2188569b3dbfc9af13/src/gcovr/logging.py#L79-L83).

The following is the error that gcovr generates unless we use
`--gcov-ignore-parse-errors=suspicious_hits.warn`:

```
[...] a bug in gcov tool, see
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68080. Use option
--gcov-ignore-parse-errors with a value of suspicious_hits.warn, or
suspicious_hits.warn_once_per_file or change the threshold for the detection
with option --gcov-suspicious-hits-threshold.

(ERROR) Error occurred while reading reports:
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/gcovr/__main__.py", line 384, in main
    covdata = gcovr_formats.read_reports(options)
  File "/usr/lib/python3.13/site-packages/gcovr/formats/__init__.py", line 99, in read_reports
    covdata = GcovHandler(options).read_report()
  File "/usr/lib/python3.13/site-packages/gcovr/formats/gcov/__init__.py", line 233, in read_report
    return read_report(self.options)
  File "/usr/lib/python3.13/site-packages/gcovr/formats/gcov/read.py", line 96, in read_report
    contexts = pool.wait()
  File "/usr/lib/python3.13/site-packages/gcovr/formats/gcov/workers.py", line 181, in wait
    raise RuntimeError(
        "Worker thread raised exception, workers canceled."
    ) from None
RuntimeError: Worker thread raised exception, workers canceled.
```

diff --git a/.github/workflows/functional-tests.yml b/.github/workflows/functional-tests.yml
--- a/.github/workflows/functional-tests.yml
+++ b/.github/workflows/functional-tests.yml
@@ -23,6 +23,7 @@ jobs:
           dnf install -y \
               autoconf \
               automake \
+              diffutils \
               gcc \
               gcovr \
               libtool \
@@ -49,7 +50,53 @@ jobs:
               --enable-module-frost
           make -j
           make check
-          gcovr --exclude 'src/bench*' --print-summary
+          # We have to add gcov-ignore-parse-errors=suspicious_hits.warn,
+          # because we found no way of generating profiles without any
+          # gcovr.formats.gcov.parser.common.SuspiciousHits error:
+          # - adding "-fprofile-update=atomic" to SECP_CFLAGS like suggested in
+          #   https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68080#c4 and
+          #   documented in
+          #   https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fprofile-update
+          #   did not help us
+          #
+          # Hence we accept to downgrade the errors to warnings, but we also
+          # check that the set of generated warnings is exactly equal to the one
+          # we are willing to allow.
+          echo "Run gcovr and capture the warnings"
+          # Run the gcovr command. Capture stderr in ACTUAL_WARNINGS for further
+          # checks. Please note that stderr is not printed in the CI console.
+          # This is tolerable because we print it immediately afterwards.
+          #
+          # Also note that we have to unset GITHUB_ACTIONS because otherwise
+          # gcovr modifies its output compared to a normal console run. Warnings
+          # would be logged twice, prepending ::warning:: the second time.
+          # For example:
+          #     (WARNING) Ignoring suspicious hits in line 'xxx'.
+          #     ::warning::(WARNING) Ignoring suspicious hits in line 'xxx'.
+          # source for gcovr's diabolic behaviour:
+          #     https://github.com/gcovr/gcovr/blob/0a426ca4baae56607f7cff2188569b3dbfc9af13/src/gcovr/logging.py#L79-L83
+          { ACTUAL_WARNINGS="$( { (unset GITHUB_ACTIONS; gcovr --exclude 'src/bench*' --print-summary --gcov-ignore-parse-errors=suspicious_hits.warn 2> >(tee /dev/fd/2 ); ) } 2>&1 1>&3 3>&-)"; } 3>&1;
+          read -r -d '' EXPECTED_WARNINGS <<-EOF || true
+          (INFO) Reading coverage data...
+          (WARNING) Ignoring suspicious hits in line '                for (p = 0; p < 16; ++p) { /* p loops over the bit positions in mul2[j]. */'.
+          (WARNING) Ignoring suspicious hits in line '                for (p = 0; p < 16; ++p) { /* p loops over the bit positions in mul2[j]. */'.
+          (WARNING) Ignoring suspicious hits in line '                    int bitpos = j * 16 - i + p; /* bitpos is the correspond bit position in m. */'.
+          (WARNING) Ignoring suspicious hits in line '                    if (bitpos >= 0 && bitpos < 256) {'.
+          (WARNING) Ignoring suspicious hits in line '                    if (bitpos >= 0 && bitpos < 256) {'.
+          (WARNING) Ignoring suspicious hits in line '                    if (bitpos >= 0 && bitpos < 256) {'.
+          (WARNING) Ignoring suspicious hits in line '                        sub |= ((m[bitpos >> 4] >> (bitpos & 15)) & 1) << p;'.
+          (INFO) Writing coverage report...
+          EOF
+          if [[ "${ACTUAL_WARNINGS}" != "${EXPECTED_WARNINGS}" ]]; then
+              printf "::error::The warnings generated by gcovr were not exactly equal to the ones we expected\n"
+              printf "EXPECTED WARNINGS:\n"
+              printf "%s\n" "${EXPECTED_WARNINGS}"
+              printf "DIFF EXPECTED -> ACTUAL:\n"
+              diff --unified <(printf "%s" "${EXPECTED_WARNINGS}") <(printf "%s" "${ACTUAL_WARNINGS}")
+              printf "::error::Failing.\n"
+              exit 1
+          fi
+          echo "OK: gcovr generated the exact set of warnings we were willing to tolerate"
       - name: Clean the build
         run: |
           make clean
